server:
  port: 8600
  servlet:
    context-path: /auth-service

spring:
  application:
    name: AUTH-SERVICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  
  # Redis Configuration for Session Management
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Mail Configuration for OTP
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      authService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

# OTP Configuration
otp:
  expiration: ${OTP_EXPIRATION:300} # 5 minutes in seconds
  max-attempts: ${OTP_MAX_ATTEMPTS:3}
  resend-cooldown: ${OTP_RESEND_COOLDOWN:60} # 1 minute in seconds

# SMS Configuration (you can integrate with your preferred SMS provider)
sms:
  api-key: ${SMS_API_KEY}
  api-url: ${SMS_API_URL}
  sender: ${SMS_SENDER:ECOMMERCE}

# External User Service URL (for user validation)
external:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8700/user-service} 