server:
  port: 8600
  servlet:
    context-path: /auth-service

spring:
  application:
    name: AUTH-SERVICE
  
  # In-memory H2 Database for development
  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  
  flyway:
    enabled: false  # Disable flyway for dev profile
  
  # Disable Redis for development
  data:
    redis:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  # Mock Mail Configuration
  mail:
    host: localhost
    port: 1025  # MailHog port if available
    username: dev@example.com
    password: dev
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  
  # Disable config server for dev
  config:
    import: "optional:configserver:"

# Development mode for testing
development:
  mode: true  # This will expose OTP codes in response for testing

# JWT Configuration
jwt:
  secret: myDevSecretKeyForDevelopmentOnlyNotForProduction
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# OTP Configuration
otp:
  expiration: 300 # 5 minutes
  max-attempts: 3
  resend-cooldown: 60 # 1 minute

# SMS Configuration (mock for dev)
sms:
  enabled: false
  api-key: dev-key
  api-url: http://localhost:3000/mock-sms
  sender: DEV

# Email configuration (disabled for dev)
email:
  enabled: false

# Session configuration
session:
  expiration: 86400000
  max-concurrent: 5

# Redis configuration (disabled for dev)
redis:
  enabled: false

# External Services Configuration
services:
  user-service:
    mock-enabled: true
    url: http://localhost:8500
    timeout: 5000

# External User Service URL (legacy)
external:
  user-service:
    url: http://localhost:8700/user-service

# Logging for debugging
logging:
  level:
    com.pm.authservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 