spring:
  datasource:
    url: jdbc:mysql://localhost:3310/payment_service?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    com.pm.paymentservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ${LOG_FILE_PATH:/app/logs}/payment-service-dev.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Payment Gateway Configuration (Development)
payment:
  gateways:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key}
      publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_your_stripe_publishable_key}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}
      api-url: https://api.stripe.com
    paypal:
      client-id: ${PAYPAL_CLIENT_ID:your_paypal_client_id}
      client-secret: ${PAYPAL_CLIENT_SECRET:your_paypal_client_secret}
      mode: ${PAYPAL_MODE:sandbox}
      api-url: https://api.sandbox.paypal.com
    vnpay:
      tmn-code: ${VNPAY_TMN_CODE:your_vnpay_tmn_code}
      hash-secret: ${VNPAY_HASH_SECRET:your_vnpay_hash_secret}
      url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    momo:
      partner-code: ${MOMO_PARTNER_CODE:your_momo_partner_code}
      access-key: ${MOMO_ACCESS_KEY:your_momo_access_key}
      secret-key: ${MOMO_SECRET_KEY:your_momo_secret_key}
      endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn}

# Service Integration
services:
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8400/order-service}
  user:
    url: ${USER_SERVICE_URL:http://localhost:8200/user-service}

# Development specific settings
debug: true
