spring:
  datasource:
    url: jdbc:mysql://payment-mysql:3306/payment_service?useSSL=true&characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=false
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 8
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: payment-service

logging:
  level:
    com.pm.paymentservice: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    root: WARN
  file:
    name: ${LOG_FILE_PATH:/app/logs}/payment-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Payment Gateway Configuration (Staging)
payment:
  gateways:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY}
      publishable-key: ${STRIPE_PUBLISHABLE_KEY}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET}
      api-url: https://api.stripe.com
    paypal:
      client-id: ${PAYPAL_CLIENT_ID}
      client-secret: ${PAYPAL_CLIENT_SECRET}
      mode: ${PAYPAL_MODE:sandbox}
      api-url: https://api.sandbox.paypal.com
    vnpay:
      tmn-code: ${VNPAY_TMN_CODE}
      hash-secret: ${VNPAY_HASH_SECRET}
      url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    momo:
      partner-code: ${MOMO_PARTNER_CODE}
      access-key: ${MOMO_ACCESS_KEY}
      secret-key: ${MOMO_SECRET_KEY}
      endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn}

# Service Integration
services:
  order:
    url: ${ORDER_SERVICE_URL:http://order-service:8400/order-service}
  user:
    url: ${USER_SERVICE_URL:http://user-service:8200/user-service}

# Staging specific settings
debug: false

# Security settings
server:
  error:
    include-stacktrace: on-param
    include-message: on-param
