spring:
  datasource:
    url: jdbc:mysql://payment-mysql:3306/payment_service?useSSL=true&requireSSL=true&characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=false
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    com.pm.paymentservice: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    root: WARN
  file:
    name: ${LOG_FILE_PATH:/app/logs}/payment-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Payment Gateway Configuration (Production)
payment:
  gateways:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY}
      publishable-key: ${STRIPE_PUBLISHABLE_KEY}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET}
      api-url: https://api.stripe.com
    paypal:
      client-id: ${PAYPAL_CLIENT_ID}
      client-secret: ${PAYPAL_CLIENT_SECRET}
      mode: ${PAYPAL_MODE:live}
      api-url: https://api.paypal.com
    vnpay:
      tmn-code: ${VNPAY_TMN_CODE}
      hash-secret: ${VNPAY_HASH_SECRET}
      url: ${VNPAY_URL:https://vnpayment.vn/paymentv2/vpcpay.html}
    momo:
      partner-code: ${MOMO_PARTNER_CODE}
      access-key: ${MOMO_ACCESS_KEY}
      secret-key: ${MOMO_SECRET_KEY}
      endpoint: ${MOMO_ENDPOINT:https://payment.momo.vn}

# Service Integration
services:
  order:
    url: ${ORDER_SERVICE_URL:http://order-service:8400/order-service}
  user:
    url: ${USER_SERVICE_URL:http://user-service:8200/user-service}

# Production specific settings
debug: false

# Security settings
server:
  error:
    include-stacktrace: never
    include-message: never
