spring:
  application:
    name: USER-SERVICE
  config:
    import: "optional:configserver:"
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://user-mysql:3306/user_service?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
    open-in-view: false
    
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  cloud:
    config:
      enabled: true
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}
      fail-fast: false

server:
  port: ${SERVER_PORT:8700}
  servlet:
    context-path: /user-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    com.pm.userservice: ${LOGGING_LEVEL_COM_PM_USERSERVICE:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:WARN}
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:WARN}
    org.springframework.cloud: WARN
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/app/logs}/user-service.log
    max-size: 10MB
    max-history: 30

# Distributed Tracing (Optional)
spring.zipkin:
  base-url: ${SPRING_ZIPKIN_BASE_URL:}
  enabled: ${SPRING_ZIPKIN_ENABLED:false}

# Custom Application Properties
app:
  name: User Service
  description: Microservice for user management, profiles, addresses, and wishlists
  version: 1.0.0 