server:
  port: 8600
  servlet:
    context-path: /order-service

spring:
  application:
    name: ORDER-SERVICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.pm.orderservice.controller
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.pm.orderservice: DEBUG
    org.springframework.web: DEBUG
  file:
    name: ${LOG_FILE_PATH:/app/logs}/order-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
