spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_stage
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8082
