spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 8082
