spring:
  datasource:
    url: jdbc:mysql://mysql:3306/product_service?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: WARN
    com.ecommerce: INFO
