version: "3.8"

services:
  payment-service:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - LOGGING_LEVEL_COM_PM_PAYMENTSERVICE=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src:ro  # Mount source for hot reload (if using dev tools)

  payment-mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3310:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
