services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT:-8700}:8700"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8700
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-mysql:3306/user_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-secret}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://eureka-server:8761/eureka/}
      - SPRING_ZIPKIN_BASE_URL=${SPRING_ZIPKIN_BASE_URL:-}
      - LOG_FILE_PATH=/app/logs
    depends_on:
      user-mysql:
        condition: service_healthy
    networks:
      - e-commerce-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8700/user-service/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  user-mysql:
    image: mysql:8.0
    container_name: user-mysql
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-user_service}
    volumes:
      - user-mysql-data:/var/lib/mysql
    networks:
      - e-commerce-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD:-secret}",
        ]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # Optional: Uncomment if Zipkin is required
  # zipkin:
  #   image: openzipkin/zipkin
  #   ports:
  #     - "${ZIPKIN_PORT}:9411"
  #   networks:
  #     - e-commerce-network

  # Optional: Uncomment if Eureka is required
  # eureka-server:
  #   image: springcloud/eureka
  #   ports:
  #     - "8761:8761"
  #   networks:
  #     - e-commerce-network

networks:
  e-commerce-network:
    driver: bridge
    name: e-commerce-network

volumes:
  user-mysql-data:
    driver: local
