services:
  user-service:
    build: .
    ports:
      - "${USER_SERVICE_PORT}:8700"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-secret}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://eureka-server:8761/eureka/}
      - SPRING_ZIPKIN_BASE_URL=${SPRING_ZIPKIN_BASE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - e-commerce-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8700/user-service/actuator/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - e-commerce-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  # Optional: Uncomment if Zipkin is required
  # zipkin:
  #   image: openzipkin/zipkin
  #   ports:
  #     - "${ZIPKIN_PORT}:9411"
  #   networks:
  #     - e-commerce-network

  # Optional: Uncomment if Eureka is required
  # eureka-server:
  #   image: springcloud/eureka
  #   ports:
  #     - "8761:8761"
  #   networks:
  #     - e-commerce-network

networks:
  e-commerce-network:
    external: true

volumes:
  mysql-data:
