services:
  user-service:
    build: .
    container_name: user-service-prod
    ports:
      - "${USER_SERVICE_PORT:-8700}:8700"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8700
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-mysql-prod:3306/user_service?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_FLYWAY_ENABLED=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - SPRING_ZIPKIN_BASE_URL=${SPRING_ZIPKIN_BASE_URL}
      - LOG_FILE_PATH=/app/logs
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_PM_USERSERVICE=INFO
      - JAVA_OPTS=-Xmx1g -Xms512m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    depends_on:
      user-mysql-prod:
        condition: service_healthy
    networks:
      - e-commerce-network
    volumes:
      - ./logs:/app/logs:rw
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8700/user-service/actuator/health",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user-mysql-prod:
    image: mysql:8.0
    container_name: user-mysql-prod
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-user_service}
      - MYSQL_USER=${MYSQL_USER:-userservice}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - user-mysql-prod-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d:ro
    networks:
      - e-commerce-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      --innodb-buffer-pool-size=256M
      --max-connections=100
      --innodb-log-file-size=64M
      --innodb-flush-log-at-trx-commit=2

networks:
  e-commerce-network:
    driver: bridge
    name: e-commerce-network

volumes:
  user-mysql-prod-data:
    driver: local
