server:
  port: 8900
  servlet:
    context-path: /content-service

spring:
  application:
    name: content-service
  
  datasource:
    url: jdbc:mysql://localhost:3312/content_service?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:content-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

logging:
  level:
    com.pm.contentservice: INFO
    org.springframework.web: INFO
  file:
    name: ${LOG_FILE_PATH:/app/logs}/content-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Content Service Configuration
content:
  blog:
    default-language: vi
    default-status: DRAFT
    auto-generate-slug: true
    auto-calculate-reading-time: true
    max-content-length: 1000000 # 1MB
  banner:
    default-type: IMAGE
    default-target: _self
    max-file-size: 10485760 # 10MB
    allowed-positions:
      - HEADER
      - FOOTER
      - SIDEBAR
      - MAIN
      - POPUP
    allowed-types:
      - IMAGE
      - VIDEO
      - HTML

# File Upload Configuration
file:
  upload:
    max-size: 10MB
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - video/mp4
      - video/webm
    storage-path: ${FILE_STORAGE_PATH:/app/uploads}
    base-url: ${FILE_BASE_URL:http://localhost:8900/content-service/files}
